services:
  - type: web
    name: prueba-render-strat-tax
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        value: sqlite:///usuarios.db